CREATE TABLE CELLAR (
id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(256) NOT NULL,
address VARCHAR(256) NOT NULL,
wineCapacity INTEGER NOT NULL,
CONSTRAINT WINECAPACITY_LESS_THAN_OR_EQUAL_ZERO CHECK (wineCapacity > 0)
);

CREATE TABLE WINE (
    id BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    cellarId BIGINT REFERENCES CELLAR (id) ,
    name VARCHAR(256) NOT NULL,
    country VARCHAR(128) NOT NULL,
    productionYear INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    type VARCHAR(5) NOT NULL,
    CONSTRAINT YEAR_LESS_THAN_OR_EQUAL_ZERO CHECK (productionYear > 0),
    CONSTRAINT QUANTITY_LESS_THEN_OR_EQUAL_ZERO CHECK (quantity > 0),
    CONSTRAINT INVALID_TYPE CHECK (type IN ('RED', 'WHITE', 'ROSE'))
)

