INSERT INTO CELLAR (name, address, wineCapacity) VALUES ('nazov1', 'adresa1', 50)
INSERT INTO CELLAR (name, address, wineCapacity) VALUES ('nazov2', 'adresa2', 100)
INSERT INTO CELLAR (name, address, wineCapacity) VALUES ('nazov3', 'adresa3', 150)
INSERT INTO WINE (cellarId, name, country, productionYear, quantity, type) VALUES (1, 'Tokaji Azsu', 'Hungary', 2005, 20, 'WHITE')
INSERT INTO WINE (name, country, productionYear, quantity, type) VALUES ('Chateau Petrus', 'France', 2000, 5, 'RED')
INSERT INTO WINE (name, country, productionYear, quantity, type) VALUES ('Quinta do Vale Dona Maria', 'Portugal', 2003, 50, 'ROSE')
INSERT INTO WINE (name, country, productionYear, quantity, type) VALUES ('Henri Jayer Richebourg', 'France', 2000, 44, 'RED')
INSERT INTO WINE (name, country, productionYear, quantity, type) VALUES ('Henri Jayer Cros Parantoux', 'France', 2003, 50, 'ROSE')
INSERT INTO WINE (name, country, productionYear, quantity, type) VALUES ('Egon Muller-Scharzhof ', 'Germany', 2005, 50, 'WHITE')
INSERT INTO WINE (name, country, productionYear, quantity, type) VALUES ('Le Pin', 'France', 2003, 50, 'ROSE')